// Generated by CoffeeScript 1.10.0
(function() {
  var api_definitions;

  api_definitions = {
    github: {
      url: function(base_url, api_version) {
        return "https://api.github.com/";
      },
      repos: "repos",
      issues: "issues",
      milestone: "milestone",
      state: "state",
      labels: "labels",
      order_by: "sort",
      sort: "direction"
    },
    gitlab: {
      url: function(base_url, api_version) {
        if (api_version == null) {
          api_version = 3;
        }
        return "https://" + base_url + "api/v" + api_version + "/";
      },
      repos: "projects",
      issues: "issues",
      milestone: "milestone",
      state: "state",
      labels: "labels",
      order_by: "order_by",
      sort: "sort"
    }
  };

}).call(this);
