#!/bin/sh
#!#/usr/bin/env bash


# GITHUB
# curl -u jneuendorf -i https://api.github.com/repos/jneuendorf/UMLEditor/issues


# GITLAB
# curl -u jneuendorf -i https://some.gitlab.com/api/v3/projects/:id/issues


# configuration file: .git-issues.json
# default url is value of .git/config->origin
# https://github.com/jneuendorf/git-issues.git (TODO strip '.git', add '/issues')

# common options:
# state	string	Can be either open, closed, or all. Default: open

# get project name from parent folder name
# parentdir=$(dirname `pwd`)

# set +x

if [[ "$1" == "fetch" ]]; then
    echo "fetch"
elif [[ "$1" == "show" ]]; then
    echo "show"
else
    echo "Usage: git-issues show|fetch"
fi
